### ISSUE TITLE
Deal with missing data directory.

### ISSUE THREAD

**Issue by LeamHall** [LeamHall/bp_tracker#1]
Create it if not present. 
Consider where it should go.

**Comment by LeamHall** [comment]
I lean towards minimal assumptions, and look for how the code might be used. My habit is to put things in $HOME/bin, and have that in my execution path. I wouldn't want to have a bit of code create a functioning directory in the root of my home directory, and if someone copies this to something like "/var/tmp/" they may not even be able to create the directory in "/var/". 

Think of how the application would be used. Someone would download it, and try to run it. If they copied the file somewhere then they have write permissions on that location. If the data directory does not exists, then the code should create it, perhaps giving a message about doing so. That way the user knows to remove the data directory and the program if they don't want to use it. 

If this is the first usage then perhaps tell them the name of the file, as well?

If they continue to use it, the data directory and file are already there.

Maybe even take a step forward and ask for permission to write the data directory before doing so?

This could lead back to your question about a config file. If we do that, do we keep it in the same directory as the program? Some Linux distros use ~/.confg for config files and ~/.local/bin for application locations. However, that may not be a good assumption, if someone uses a Mac or Winderz machine. This is why I use a "data/" directory relative to the program itself, less hassle trying to figure out multiple OS idiosyncrasies.

**Comment by alexKleider** [comment]
Currently the system assumes /data/bp_numbers.text is the data file.
Comments suggest we consider adding an '-i datafile' option to over-ride the default /data/bp_numbers.txt.
Should this issue then concern itself with adding such an -i option?
The issue of whether or not to have a config file still stands: if one does use an -i option is it only effective for that one run of the program or should it reset the default data file in which case we'll need a config file.
If we do use a config file I suggest bp.config right along side bp_tracker.py.
We need to make a decision about these issues before beginning to address issue_001

**Comment by alexKleider** [comment]
Reading your comments above, the following comes to mind:
So we agree on using a "data/" directory relative to program itself.
Perhaps that's the place to put a config file!
If bptracker.py is in $HOME/bin then the config file will be in
$HOME/bin/data
... are we OK with that?
OR should we assume that the program is installed with
git clone github.com/leamhall/bp_tracker
in which case (assuming this is done from within the $HOME/bin
directory) bp_tracker.py and data will be in $HOME/bin/bp_tracker.
If we have a config file, then the -f option can be fixed to simply modify the config file and do nothing else.
As things currently stand, it serves only to direct data to be sent to or read from a file other than the default file.

**Comment by LeamHall** [comment]
We'll go with the default of the data file being in the same directory, and keep the user's option to pick a different file/location as they see fit. That helps us avoid having to code around a lot of possibilities, and focus on what we do best.
