### ISSUE TITLE
issue_010: failure of -f option

### ISSUE THREAD

**Issue by alexKleider** [LeamHall/bp_tracker#10]
use of -f option raises:
Error processing report data integer division or modulo by zero

Discovered as I was trying to address issue_001

**Comment by LeamHall** [comment]
I'm not seeing an issue. I have a fresh copy of the master branch, and I used the -f options with your data file, mine, and a non-existant file. How are you generating this error?

**Comment by alexKleider** [comment]
Can't seem to recreate it. (... as described in earlier email.)
Let's forget about the "problem" for now. Perhaps it'll never arise again. (I hope!)
a

Alex Kleider (set from my current gizmo)

------- Original Message -------

**Comment by alexKleider** [comment]
False alarm (or at least for now, can not recreate the error and Leam doesn't get the error either.)
