### ISSUE TITLE
Get rid of decimal places in display_averages,

### ISSUE THREAD

**Issue by LeamHall** [LeamHall/bp_tracker#20]
It is overly precise for the task at hand. Of course, we don't have a final output format, so is this even needed?

**Comment by alexKleider** [comment]
This is a trivial fix.
As soon as you approve issue_009 I can take care of this in a matter of minutes.

Alex Kleider (set from my current gizmo)

------- Original Message -------

**Comment by alexKleider** [comment]
Done and passing test.
Waiting for OK 2 merge issue_020 into master
(or preferably have you (Leam) do it. I'm not sure what series of commands to use to do that.)

**Comment by LeamHall** [comment]
Got rid of display_averages.
