### ISSUE TITLE
Shorten the return statement:   return [round(val/n) for val in (sys_sum, dia_sum, pul_sum)]

### ISSUE THREAD

**Issue by LeamHall** [LeamHall/bp_tracker#21]
Make it simpler. The entire method may welcome simplification.

**Comment by alexKleider** [comment]
Again, make some suggestions.
There are many ways to skin a cat.
If you don't like my way, suggest one better; I'm open.
a

Alex Kleider (set from my current gizmo)

------- Original Message -------

**Comment by LeamHall** [comment]
Took your "data", pulled out the two lists we're reporting on, and re-wrote format_report to deal with those lists.
