### ISSUE TITLE
User integer division vice round()

### ISSUE THREAD

**Issue by LeamHall** [LeamHall/bp_tracker#22]
Fewer characters, easier to read. No practical loss in accuracy.

average = round(sum(l) / len(l))

**Comment by alexKleider** [comment]
I've already explained why this was changed to use round.
The other way of dealing with the inconsistency problem would be to change the other code that calculates average. In fact we should probably look for where averages are calculated and see if we can change the code so there is only one place where this is done (and always done the way that suits you the best.)

Alex Kleider (set from my current gizmo)

------- Original Message -------

**Comment by LeamHall** [comment]
round() is gone.
