### ISSUE TITLE
Identify BP guidelines that cover both high and low blood pressures.

### ISSUE THREAD

**Issue by LeamHall** [LeamHall/bp_tracker#25]
There are probably people that need it.

**Comment by alexKleider** [comment]
does get_category not already provide what you are wanting?
...or am I not understanding what you really want?

**Comment by LeamHall** [comment]
Needed a simpler layout, used systolic_labels, and diastolic_labels.

**Comment by alexKleider** [comment]
Agreed, I believe get_category already does that or did you have something else in mind?

Alex Kleider (set from my current gizmo)

------- Original Message -------
