### ISSUE TITLE
Move "Tests" to "test"

### ISSUE THREAD

**Issue by LeamHall** [LeamHall/bp_tracker#4]
"test" is the usual Python name for the test directory.

**Comment by alexKleider** [comment]
Yes.
I've long before I knew about Python or git and was just getting to know Linux adopted the habit of naming directories with a capitol first letter (so I could tell at a glance what were directories and what were text files (I didn't have much else that interested me at that time.)
I still like to use that convention but recognize that no one else does.
... so "tests" it is:-)
a

Alex Kleider (set from my current gizmo)

------- Original Message -------

**Comment by LeamHall** [comment]
I'm not sure why, but in the source code for Python itself, they use "test" in the singular. I'd like to align with that, even though my first thought was "tests" in the plural.

Running tests from the project root directory doesn't seem to work:

`python -m unittest`

That seems to be the preferred way to run tests, since you can run lots of them with one command. How were you running the tests?

**Comment by alexKleider** [comment]
Here's how I've been doing it:
(p9) ***@***.***:~/Git/LH2/bp_tracker$ ./tests/bp_test.py
but I agree, that your command should be made to work.
I've submitted another push (git push origin --set-upstream issue_004b) which deletes the bothersome 's'. (python -m unittest now functions as we'd expect.)
Should I be merging locally or should you be merging and then I'll do a pull from the master branch?
a

Alex Kleider (set from my current gizmo)

------- Original Message -------

**Comment by LeamHall** [comment]
To make your life easier, don't worry about making branches for corrections in an issue branch. We can use the same branch, "issue_004" or whatever, to bounch changes back and forth. Once everything is good, we can the merge into master.

In this instance, we can stick with issue_004b and move forward. The tests aren't working for me, though. We should be able to run it with just the 'unittest' module, and it autodiscovers:

```
python -m unittest
----------------------------------------------------------------------
Ran 0 tests in 0.000s
OK
```

However, even calling it directly seems to have issues:
```
python -m unittest test/bp_test.py 
EE
======================================================================
ERROR: test_averaging (test.bp_test.TestBpTracker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/leam/lang/git/LeamHall/bp_tracker/test/bp_test.py", line 51, in test_averaging
    bp_tracker.averages(
AttributeError: module 'bp_tracker' has no attribute 'averages'
======================================================================
ERROR: test_averaging_only_last_few (test.bp_test.TestBpTracker)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/leam/lang/git/LeamHall/bp_tracker/test/bp_test.py", line 61, in test_averaging_only_last_few
    bp_tracker.averages(
AttributeError: module 'bp_tracker' has no attribute 'averages'
----------------------------------------------------------------------
Ran 2 tests in 0.001s
FAILED (errors=2)
```

I made some changes on branch issue_004b. let's stick with that for now, and if you do a "git pull", and checkout that branch, it should let you run the tests with "python -m unittest".  I removed the "sys" references, too.
