### ISSUE TITLE
Draft end state results layout

### ISSUE THREAD

**Issue by LeamHall** [LeamHall/bp_tracker#6]
The thought on this is to provide a quick check on the current BP results compared to where they "should be". The ideal is less than 120/80, but someone with much higher numbers may need to see the first goal as a more reasonable set, like less than 140/90 (Into the Prehypertension level).  For example:

```
PreHyper   Current   Average
 < 140       147      143
 <  90        96       92

```
That provides a very quick visual indicator: "Where do I need to be", "Where am I right now", and "How am I trending towards my next goal?"

**Comment by alexKleider** [comment]
This implies (pretty explicitly actually) that there must be a "should be" level specified somewhere.
That would be a different number for each user.
How would one specify it (a separate command presumably?)
A bigger problem is where would that specification be kept- each user would have to have their own!
Does that get us back to the need for a config file?
Should it be a specially marked (prefaced by "#!" perhaps) line in the data file?

**Comment by LeamHall** [comment]
Yes, think about the various "levels" of hypo/hyper tension, and the slow rate of change for these numbers. The results should give the next goal to reach for each specific number, since life-style changes that impact systolic aren't always the same for diastolic. 
This needs to cover both hypo and hyper tension; I think I shared some coude else where that is a start, but I wanted to get issue 11 resolved and merged.

**Comment by alexKleider** [comment]
I believe issue 11 is history. (Can't remember how long ago it's been closed; I don't believe I closed it. Can't remember what it was  even.)
What exactly you want here is a little fuzzy (to me at lease.)

**Comment by alexKleider** [comment]
I was mistaken; issue 11 was mine and closed long ago (I hope with your approval.)

**Comment by LeamHall** [comment]
Current output format:
Systolic 141 (high: stage 2) 
Diastolic 62 (low) 
Average 129/65 

Removed a lot of code that does not support the output.
